## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapl-16
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapl-16
  template:
    metadata:
      labels:
        app: webapl-16
    spec:
      securityContext:
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: nginx
        image: maho/nginx:1.25.2
        securityContext:
          allowPrivilegeEscalation: false
