## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapl-16
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapl-16
  template:
    metadata:
      labels:
        app: webapl-16
    spec:
      containers:
      - name: nginx
        image: nginx:1.20.2


