## サービス
apiVersion: v1
kind: Service
metadata:
  name: webapl-16
spec:
  selector:
    app: webapl-16
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: https
    protocol: TCP
    port: 443
  type: LoadBalancer
